# Generated by Django 3.0.5 on 2020-09-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carauselImgs',
            fields=[
                ('display_img_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=50)),
                ('display_img', models.ImageField(upload_to='updateSystem/images')),
            ],
        ),
    ]
