# Generated by Django 3.0.5 on 2020-09-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateSystem', '0002_carauselimgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carauselimgs',
            name='display_name',
            field=models.CharField(max_length=150),
        ),
    ]
