# Generated by Django 3.0.5 on 2020-09-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateSystem', '0004_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='product_image1',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(null=True, upload_to='updateSystem/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(null=True, upload_to='updateSystem/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image4',
            field=models.ImageField(null=True, upload_to='updateSystem/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image5',
            field=models.ImageField(null=True, upload_to='updateSystem/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
