# Generated by Django 3.0.5 on 2020-09-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateSystem', '0005_auto_20200913_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
