# Generated by Django 3.0.5 on 2020-09-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateSystem', '0006_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
