# Generated by Django 3.0.5 on 2020-09-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateSystem', '0009_auto_20200914_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
